### ISSUE TITLE
Document launching an interview checklist

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/AssemblyLine-docs#435]
In the interview building project template the final step is to launch the interview, but the documentation should probably have a similar checklist of recommended steps.

From the interview project template:

* [Complete the draft interview for its first demo](https://github.com/orgs/SuffolkLITLab/projects/22?pane=issue&itemId=61504799)
* [Finalize the interview and prepare it for launch](https://github.com/orgs/SuffolkLITLab/projects/22?pane=issue&itemId=94972463)
* [Launch the interview!](https://github.com/orgs/SuffolkLITLab/projects/22?pane=issue&itemId=61508986)

**Comment by samglover** [comment]
Below is an action workflow script that creates an annual issue to check the interview for updates that might be necessary. Something like it should be added to all live interviews on launch.

File location/name: `.github/workflows/update-interview.yml`

```
name: Annual update interview issue
on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "33 3 1 7 *" # At 3:33am every August 1st

jobs:
  create_issue:
    name: Create update-interview issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create update-interview issue
        run: |
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --body "$BODY")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Check this interview for updates
          BODY: |
            - [ ] Check for errors by running through the interview several times. Use different inputs each time.
            - [ ] Check for new versions of the PDF or DOCX forms in the `data/templates` folder.
            - [ ] Check for updates to the law(s) on which the interview is based.
            
            If any of the above reveal a need to update this interview, do the following:
            * Describe the updates necessary in a comment on this issue.
            * Un-assign yourself from this issue
            * Change the project selection for this issue to the Interview Upkeep project.
```

**Comment by samglover** [comment]
Couple more things to add to the launch checklist:

* Review repository access settings.
* Add a branch protection ruleset. Here are the settings I think we want:
  - Target `main` or `master`
  - Restrict deletions
  - Require a pull request before merging (i.e., no direct commits)
  - Block force pushes
  - Require status checks or code scanning?

**Comment by samglover** [comment]
Another suggestion, for READMEs:

# [JURISDICTION] [FORM(S)]
This is a Docassemble interview to complete the [JURISDICTION] [FORM(S)] online.

The default README is just a little too hard to read, and authors may not want their names shown publicly (although if they want to, it's fine to leave it in).

**Comment by samglover** [comment]
Here is an [older Document Assembly Line launch checklist](https://sumail.sharepoint.com/:w:/r/sites/LegalInnovationandTechnologyLab/Shared%20Documents/General/Checklists/Go%20live%20checklist%20for%20first%20Assembly%20Line%20interview.docx?d=w77d1f00227ba419183402d80084a9099&csf=1&web=1&e=BTptE7).
