### ISSUE TITLE
Document some more style guide stuff (checklist)

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/AssemblyLine-docs#440]
- [ ] Whether to use title case or sentence case for the name of a document? (avoid using the proper name, but when it is the proper name it should be title case)
- [ ] Only include the form number in the title of the interview if it is well known and would help the user find the right interview
- [ ] State a preferred verb for verbing a court form (make, fill out, complete)
- [ ] Common word-choice preferences:
  - [ ] Welfare: well-being
  - [ ] Interested person: someone who ...

**Comment by nonprofittechy** [comment]
Also see: https://www.mass.gov/doc/readability-guidelines-for-printed-self-help-materials-and-forms/download#:~:text=9.,Date%20all%20documents.

**Comment by nonprofittechy** [comment]
Conventions for when to use the first name
